title: DupeClient Wiki
description: Full usage guide for the DupeClient Fabric mod
theme: jekyll-theme-cayman
markdown: GFM
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
